version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.19 # 使用 CircleCI 提供的默认 Go 环境镜像
    steps:
      - checkout # 检出代码
      - run:
          name: Install Build Dependencies
          command: apk add --no-cache gcc musl-dev
      - run:
          name: Build Application
          command: |
            go mod tidy
            CGO_ENABLED=0 GOOS=linux go build -o socks5-proxy ./cmd/main.go
      - run:
          name: Verify Binary
          command: ./socks5-proxy --help || echo "Build successful"

  docker_build:
    docker:
      - image: circleci/docker:latest # 使用 CircleCI 默认 Docker 镜像
    steps:
      - checkout
      - setup_remote_docker # 启用 Docker 环境
      - run:
          name: Build Docker Image
          command: docker build -t socks5-proxy .
      - run:
          name: Test Docker Image
          command: |
            docker run --rm socks5-proxy --help || echo "Docker image is valid"

workflows:
  version: 2
  default:
    jobs:
      - build
      - docker_build:
          requires:
            - build
